chaoss/grimoirelab

- CONTRIBUTING.md
According to what was proposed in the mailing list, find here the first version of the contributing rules and information.
> Add contributing rules and info.

- releases/NEWS
I've tried to recover as much useful information about coordinated releases from internal Bitergia tickets. This could be useful in the future, maybe...
> Add NEWS file, with history of coordinated releases since atom_girl

- tests/README.md
- tests/docker-compose-local.yml
- tests/docker-compose.yml
The default configuration for docker-compose exposed the
Kibana and ElasticSearch ports to the host. This causes
trouble if there are local instances of any of them
already running in the host, or if those ports are busy
for some other reason.
To avoid this problem, docker-compose.yml now avoids
to expose those ports. But the functionality provided
by the previous docker-compose.yml file is still
provided by using -f option to docker-compose,
and docker-compose-local.yml, see current version of
README.md for details.
> [tests] Slightly simplified docker-compose.yml

- tests/Dockerfile
- tests/README.md
- tests/docker-compose.yml
- tests/stage
- utils/build_grimoirelab
This patch changes:
* The base container used for the mordred service in docker-compose.
Now, it is based on Debian9 (since the script below needs
Python3.5), and only minimal packages are installed
(including almost no Python modules, which will be installed later).
* The docker-compose file is simplified, using the
utils/build_grimoirelab script.
* The utils/build_grimoirelab script was fixed to work well when
installing in the system (instead of in a virtual environment).
* tests/README.md is updated to reflect some of these changes.
For now, it only installs the master/HEAD for all GrimoireLab repos,
but it could be easily modified to install any coordinanted
release.
> [tests] New mordred container

- tests/Dockerfile
- tests/docker-compose.yml
- tests/stage
- utils/build_grimoirelab
Dependencies could not be installed from wheels because the wheel package was not installed. This patch installs it. A new Python dependency is not available in binary wheels, so it needs to be compiled. But there was no compiler in the base container. So, this patch installs it.
There are some other (hopefully minor) issues fixed too.
Please, try this from scratch, as follows:
```
$ docker build -t grimoirelab/basic .
$ docker-compose -f docker-compose.yml -f docker-compose-local.yml mordred
```
(although it is very likely that you really don't need the two `-f` parameters in the second command)
This is a quick patch, trying to make the stuff work. I'm still working in more testing and a better solution.
> [tests] Fix docker cointainers configuration info

- utils/build_grimoirelab
When installing from already produced packages, --build should no longer be a default action. Therefore, now if you want --build and --install, you need to specify both.
> [build_grimoirelab] --build is no longer a default action

- utils/build_grimoirelab
Some repos (kidash, manuscripts) are alread in the chaoss organization, so we need to update that data for building those repos.
Added a new field (repo_url) for the url of the repo, since we're no longer using always the same prefix.
> [build_grimoirelab] Updated to new repos in chaoss organization

- docker/Dockerfile-full
- docker/README.md
- docker/entrypoint-full.sh
Now Dockerfile-full installs Elasticsearch 6.1 and Kibiter 6.1.
All GrimoireLab tools already support these versions, except some minor issues with panels.
> [docker] Support for Elasticsearch 6.x

- CONTRIBUTING.md
Minor change to reference the list of repos now that we moved to CHAOSS.
valcos was admitted as general committer after a vote in the mailing list.
> [CONTRIBUTING] Add valcos as general committer, update of reference to repos

- utils/build_grimoirelab
This is a first try at improving the testing when producing packages for Pypi. Two new checks have been included:
* That each module can be installed alone (with its dependencies)
in a virtual environment.
* That one executable can be run for each package. Usually,
for each package, the main executable is run with the "--help"
argument.
The structure of the script is now more complete, paving the way for running the unit tests of each module.
Running build_grimoirelab as follows, uncovered three cases of packages that, when installed alone with their dependencies, cannot be run:
```
./build_grimoirelab --check --distdir /tmp/dist --reposdir /tmp/repos --relfile ../releases/18.04-02 --fail
...
Failed check run (grimoire-elk)
Failed check run (kidash)
Failed check run (grimoire-mordred)
``` …
> [build_grimoirelab] Add check that tools can be run

- utils/README.md
- utils/build_grimoirelab
In some cases, some of the standard upstream repos, which are those that build_grimoirelab uses by default, need to be replaced (or augmented) with other repositories, such as local clones of the repos, with local modifications to test.
This patch adds a new argument, reposfile, to specify a JSON file with a dictionary, in the same format as the variable for default repos (variable all_repos in build_grimoirelab).
> [build_grimoirelab] Add argument for specifying repos to build

- utils/README.md
- utils/build_grimoirelab
This patch improves support for testing GrimoireLab pip packages. Now, it allows to run `setup.py test` for each module, including configuration files for testing (eg, when they are needed to express addresses or credentials to access services). One of the commits also removes the need to build before testing, allowing that way to test already built packages (in fact, they will be used as dependencies, since unit tests will always be run on the source code).
Now, all build packages for a GrimoireLab distro can be tested by running (assuming built packages are in `dist`, configuration files for testing are in `testconf`, which will have one subdirectory per module with testing config files, with the same path they should be copied to the source code repo befor running tests, and `release` …
> [build_grimoirelab] Improve support for testing

- docker/ansible_release.yml
- utils/build_grimoirelab
This includes two commits:
* Ansible playbook now allows for overriding the default behavior of failing if there are errors when building, installing or testing packages.
* `build_grimoirelab` now uses absolute paths for the dist directory.
> Improvements for bulding packages

- utils/README.md
- utils/build_grimoirelab
New options to build_grimoirelab to obtain the top level dependencies for a GrimoireLab release (that is, the list of modules and their version numbers), suitable for use in a requirements.txt file.
> [build_grimoirelab] Add support for obtaining GrimoireLab dependencies

- bin/grimoirelab
- grimoirelab_pkg/__init__.py
- grimoirelab_pkg/_version.py
- setup.py
This package will be mainly for a simple installation of a GrimoireLab release. The idea is that this package
pulls, via dependencies, from all GrimoireLab packages in a release, as specified in the requirements.txt file.
Usually, requirements.txt and grimoirelab/_version.py will be updated in the same commit, thus freezing
a certain version of the packages. Usually, this will be done after, or in the same commit, the file in releases
corresponding to the release is committed.
Temporarily, while the module name grimoirelab is freed by the grimoirelab-toolkit package, we're using
grimoirelab_pkg as the name for this module. This will change to grimoirelab as soon as possible.
> Create structure for a grimoirelab Python package.

- docker/README.md
- docker/ansible_release.yml
- docker/entrypoint-full.sh
In some cases, you want to produce container images and Python packages even if tests or checks fail. This code improves this case.
> [docker] Improve code for allowing tests not to fail.

- utils/build_grimoirelab
When no release file is provided, build_grimoirelab uses master for
all GrimoireLab git repos as the version to build. Instead of "Unknown",
let's call this "Current master from git repos"
> [build_grimoirelab] Switch to better message when no release file

- docker/mordred-infra.cfg
If not, the container, by default, fails.
> [docker] Add new kibiter_url entry to infra.cfg

- MANIFEST.in
This way, setup.py can be run when neeeded (it reads requirements.txt).
> [setup] Add requirements.txt file to manifest.

- README.md
This code modifies the README.md file to include the link to the GitHub repository hosting Graal.
> [doc] Update README.md to include Graal repository

- CONTRIBUTING.md
Since today, contributions will need a DCO in all GrimoireLab repos.
This patch updates `CONTRIBUTING.md` accordingly.
Fix #188
> [CONTRIBUTING.md] Adding info about DCO

- docs/index.html
Still need to test this locally, but it appears the `about` link at the top of the page isn't correctly pointing to the footer element. Not sure if this is a jekyll problem or what, but this more direct link should work.
> fix frontmatter link to about page

- default-grimoirelab-settings/apache-hatstall.conf
- default-grimoirelab-settings/shdb.cfg
- docker-compose/docker-compose-secured.yml
- docker-compose/docker-compose.yml
Hatstall is missing its configuration, without which the user will just see the default Apache httpd landing page.  This commit adds the example configuration taken from the [Hatstall repo](https://github.com/chaoss/grimoirelab-hatstall).
Signed-off-by: Nick Jones <nick@dischord.org>
> Add missing Hatstall configuration

- docker/Dockerfile-full
Update the Kibiter version to address the [issues](https://github.com/chaoss/grimoirelab-kibiter/issues/119) found in version 6.1.4-1 in Docker images.
> chore: update kibiter version

- default-grimoirelab-settings/setup-secured.cfg
- default-grimoirelab-settings/setup.cfg
- docker-compose/docker-compose.yml
This PR updates the setup.cfg files by removing the `bots_names` attribute and increase the image version number of mordred, which is now 0.2.33
> Update docker compose settings

- default-grimoirelab-settings/setup-secured.cfg
The 'setup-secured.cfg' had some content that diverged from the unsecured cfg version. 
This PR makes them more alike so that the differences become more apparent.
> make the setup-secured.cfg more like the unsecured cfg

- third-party/Dockerfile-fossology
- third-party/Dockerfile-grimoirelab-nomos
- third-party/README.md
- third-party/entrypoint-fossology.sh
For now, it inclues Dockerfiles and other related files to produce FOSSology Debian packages, via a Docker container, and a Docker container like grimoirelab/full with nomos also installed.
> New directory for third party tools of interest for GrimoireLab

- docker-compose/README.md
I have provided a fix for the clone URL.
This being said, I guess it could be improved : currently we're pulling 265MB of data from github just to get the docker-compose files.
> fix update clone url

- docker-compose/docker-compose-secured.yml
- docker-compose/docker-compose.yml
This PR addresses https://github.com/chaoss/grimoirelab/issues/283, thus it deletes the param `ports` to prevent the exposure of mysql/mariadb ports.
> [docker-compose] Prevent exposure of mysql db ports

- docker/Dockerfile-installed
This PR addresse https://github.com/chaoss/grimoirelab/issues/289, thus it includes some packages needed to export reports correctly.
> [docker] Add latex packages to Dockerfile

- third-party/README.md
This code adds the instructions needed to build the image and run the container able to derive sentiment and emotion information from text. Full details can be found at: https://github.com/Danny2097/CROSS-NLP-REST-API
This PR replaces https://github.com/chaoss/grimoirelab/pull/259, which was proposing to modify the dockerfile of the third-party image
Related to https://github.com/chaoss/grimoirelab/issues/258
> [third-party] Add doc to get sentiment and emotion data

- third-party/README.md
This code removes the param `git-path` from the example of the setup.cfg in the README. This change is due to the fact that when the git-path is set and multiple repos are defined in the projects.json, they are cloned in the same folder and their info is mixed together.
Related to https://github.com/chaoss/grimoirelab-graal/issues/86
> [third-party] Remove param git-path from setup.cfg

- third-party/Dockerfile-grimoirelab-3p
This PR addresses https://github.com/chaoss/grimoirelab/issues/262
This code includes the Jadolint tool (available at https://github.com/crossminer/crossJadolint), which
is able to extract dependencies from Dockerfiles.
The dockerfile grimoirelab-3p file has been modified to download and compile this tool.
Things to be done:
> [third-party] Add Jadolint tool

- README.md
Following the discussion at https://github.com/chaoss/grimoirelab-sirmordred/pull/428#discussion_r392673442, this PR adds a picture of GrimoireLab to the README.md as a showcase.
Do you think if it would good if the picture goes above `# GrimoireLab` in the README?
> [README] Add a picture of GrimoireLab

- docker-compose/docker-compose-secured.yml
- docker-compose/docker-compose.yml
This code removes the redis service, since not used anymore by the platform. Furthermore, the mordred image is updated to 0.2.39.
> [docker-compose] Remove redis and update mordred image

- default-grimoirelab-settings/aliases.json
- docker-compose/docker-compose.yml
- docker/aliases.json
This PR updates:
- the kibiter image used in the docker-compose to 6.1.4-3, since the network plugin isn't loaded in the current version.
- the aliases.json file which was changed (https://github.com/chaoss/grimoirelab-sirmordred/commit/b6fa5962bfc5dcb7cc779a71586d91c92f3a7057) to deal with complex aliases.
> Update aliases.json and kibiter version

- docker-compose/docker-compose-secured.yml
- docker-compose/docker-compose.yml
This code allows to use the latest mordred image available on dockerhub. This tag is added when
generating the release.
> [docker-compose] Use latest tag

- docker-compose/docker-compose-secured.yml
- docker-compose/docker-compose.yml
This code updates the docker-compose files by changing the elasticsearch and kibiter sections
to use the images for ES/Kibiter 6.8.
> [docker-compose] Update images to ES/Kibiter 6.8

- default-grimoirelab-settings/setup.cfg
As per other data sources, it may be useful for newcomers to have a commented out configuration for the discourse backend.
This configuration information was given in [issue #132 of grimoirelab-tutorial](https://github.com/chaoss/grimoirelab-tutorial/issues/132)
> Add discourse example in setup.cfg

- README.md
The components section was missing three repos,
Kidash, Cereslib and Perceval Weblate. This commit adds
those components in the README.md
Signed-off-by: sevagenv <sevagenv@gmail.com>
> [README] Add missing components

- CONTRIBUTING.md
- docs/_includes/footer.html
This PR replaces the IRC chat links with the slack group. We want to use slack for communication and need this change on the website and CONTRIBUTING.md docs.
Closes https://github.com/chaoss/grimoirelab/issues/431
> Replace IRC links with Slack

- community_components.md
This commit adds the Gitee support for GrimoireLab information to the community components file.
The support for grimoirelab-gitee was developed by @WillemJiang, @heming6666, @eyehwan, and @shanchenqi.
Related to #439
> Add grimoirelab-gitee to community_components.md

- README.md
- docs/_includes/footer.html
- docs/index.html
- Updated the README.md file to also contain the link to the contributing guidelines (CONTRIBUTING.md)
- Updated the landing page for GrimoireLab to display the link to the Contributing Guidelines, since the website did not mention them anywhere. 
This can increase the ease and accessibility with which users may refer to the guidelines.
Resolved issue: [#342](https://github.com/chaoss/grimoirelab/issues/342)
> Making the 'How to contribute to GrimoireLab' more visible

- .github/workflows/release.yml
- pyproject.toml
This PR adds the release GitHub action which generates a package, tests it can be installed with different Python versions, publishes the release on GitHub, and uploads the packages to PyPI whenever a tag is generated and pushed.
> [gha] Create release.yml

- pyproject.toml
This PR updates the dependencies of this package and includes `allow-prerelease` option to all grimoirelab dependencies.
> [poetry] Allow Grimoirelab prereleases in dependencies

- .github/workflows/release-grimoirelab-component.yml
This PR includes a new step in the package release. When the release finishes, it waits until the package is ready in PyPI.
- One example that continues: https://github.com/jjmerchante2/grimoirelab/runs/8227716278?check_suite_focus=true#step:12:1
- Another example that keeps waiting and canceled manually: https://github.com/jjmerchante2/grimoirelab/runs/8227858527?check_suite_focus=true#step:12:1
> [release] Wait for packages ready in PyPI before continuing

- .github/workflows/release-grimoirelab-component.yml
This commit updates the release workflow. Now it will check if the package is ready with 'pip index versions' instead of trying to install the package.
Signed-off-by: Jose Javier Merchante <jjmerchante@bitergia.com>
> [release] Check if packages are ready with 'pip index versions'

- .github/workflows/release-grimoirelab-component.yml
This commit stores the output of `pip index version` in a file instead of redirecting the output to a pipe because it seems not to be allowed.
https://github.com/jjmerchante2/grimoirelab/runs/8273848644?check_suite_focus=true#step:12:1
> [release] Update a bug in the 'pip index version'

- .github/workflows/grimoirelab-release.yml
- .github/workflows/release-grimoirelab-component.yml
Check if dependencies are available before running `poetry update`. This way we can ensure the package exists for Poetry and if it fails later something is wrong with it.
> [release] Verify if dependencies are ready in PyPI

- .github/workflows/release-grimoirelab-component.yml
This PR updates Poetry's command that checks for new versions including --no-cache in case it is taking the latest version from the cache and changing the retry to exponential backoff.
> [release] Poetry no cache exponential retry

- .github/workflows/release-grimoirelab-component.yml
This PR fixes a bug where bash doesn't detect a regular expression that includes quotes.
> [release] Remove the quotes around regex

- .github/workflows/grimoirelab-release.yml
This PR fixes an issue that didn't allow triggering the `release.yml` workflow from `grimoirelab-release.yml` when creating a new tag from the same repository.
`actions/checkout` allows to include a token variable that by default is `github.token` and is persisted in the local git config, which makes that defining the token in any other way doesn't use it.
The default `github.token` prevents you from accidentally creating workflow runs, that's why it didn't trigger a new
workflow when it creates a new tag.
Closes https://github.com/chaoss/grimoirelab/issues/525
> [release] Fix workflow triggering from another workflow

- .github/workflows/docker-image.yml
- .github/workflows/grimoirelab-release.yml
- .github/workflows/release-grimoirelab-component.yml
- .github/workflows/release.yml
This PR updates the version number of the actions being used. Now they will use the commit SHA of a released action version because it is the safest for stability and security.
> [actions] Include SHA version of the action used

- .github/workflows/grimoirelab-release.yml
- .github/workflows/release-grimoirelab-component.yml
This PR changes deprecated `set-output` commands and starts using environment files as requested by GitHub.
This PR also generates random delimiters for each run to avoid script injection attacks when managing release notes
This PR avoids updating NEWS files in release candidate versions.
> [release] Fix deprecated set-output commands in GH actions

- docker/stage
This code removes temporary `perceval` files after a restart to avoid filling up the disk.
Signed-off-by: Quan Zhou <quan@bitergia.com>
> [docker/stage] Remove temporary perceval files

- .github/workflows/release-grimoirelab-component.yml
This commit changes the way it waits for dependencies. Now it sleeps 60 seconds instead of running poetry add.
> [release] Wait for dependencies to be ready

- .github/workflows/grimoirelab-release.yml
- .github/workflows/release-grimoirelab-component.yml
This PR updates the way the release workflow waits for the dependencies. For all the repositories it waits until dependencies are ready except for ELK and Sirmordred that Poetry spends 1 hour to check if all the dependencies are ready and are substituted with 60 seconds.
> [release] Wait for Poetry packages in GitHub workflow

- .github/workflows/grimoirelab-release.yml
- .github/workflows/release-grimoirelab-component.yml
- docker/Dockerfile
This PR updates how the release workflow checks the new version number for GrimoireLab.
Each package indicated the version changed in the previous version, but that method isn't idempotent when the workflow is
restarted.
Now is the last step when the version is calculated based on the packages installed in GrimoireLab and the new version for each package.
This PR also includes the `--pre-release` argument to `notes` when it is a release candidate version to execute that command according to the new changes in `release-tools`.
_Depends on `release-tools` Pull Request._
> [release] Update GrimoireLab version and include --pre-release to notes

- .github/workflows/grimoirelab-release.yml
- .github/workflows/release-grimoirelab-component.yml
This PR fixes the semverup command that didn't have the argument for the release candidate.
It also removes the 180 seconds wait time for packages that haven't got dependencies.
Include `grimoirelab-panels` in the version comparison check.
> [release] Fix release candidate bug and wait for release

- .github/workflows/release-grimoirelab-component.yml
This PR substitutes the poetry command to check if the packages are available to speed up the process.
Is much faster to clear the Poetry cache and run a command than running it with `--no-cache`.
> [ci] Clear Poetry cache instead of running with `--no-cache`

- .github/workflows/release.yml
This PR updates the version of the release GitHub action to use `ubuntu-latest` instead of `ubuntu-18.04` wich is deprecated.
More info: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
> [ci] Update deprecated ubuntu-18.04 of GitHub Actions

- .github/workflows/grimoirelab-release.yml
- .github/workflows/release-grimoirelab-component.yml
This PR standardizes the way the packages wait for dependencies ready in PyPI. Previously, certain packages required a sleep delay because the Poetry command was slow. That issue was addressed, and now it checks the dependencies more efficiently.
> [release] Check dependencies in PyPI instead of sleep

- .github/workflows/release.yml
- poetry.lock
- pyproject.toml
This PR removes statsmodels as a direct dependency.
> [pyproject] Remove statsmodels dependency

- .github/workflows/release.yml
This PR includes a new input to the `build` action of the release to pin the dependencies of the GrimoireLab package.
> [actions] Pin GrimoireLab depnendencies

- .github/workflows/docker-image.yml
This PR fixes a bug that causes cosign v2 not to sign the images provided by docker_meta.tags.
> [docker] Fix a bug preventing image signing with cosign

- CONTRIBUTING.md
- CONTRIBUTING_WITH_CODE.md
- GOVERNANCE.md
- MAINTAINERS.md
Governance rules have been updated to make them more clear and to align the project with CHAOSS. This commit also improves the rules and recommendations for contributing to the project.
> Update governance rules for GrimoireLab project

- docker/Dockerfile
The grimoirelab container uses `${DEPLOY_USER_DIR}` as working directory, but created a volume under `/home/bitergia/logs`. This commit fixes the path of the log volume, which makes it possible to start grimoirelab container with a read-only root filesystem.
> Create log volume matching ${DEPLOY_USER_DIR}

- ADOPTERS.md
- CONTRIBUTING.md
The purpose of this file is to show how organizations and users are using GrimoireLab. We took this idea from the Kyverno project.
> Add adopters file

- .github/workflows/grimoirelab-release.yml
Use the release notes from `releases/custom_releases_notes.md` when defined instead of the notes from each component.
> [release] Use custom release notes when defined

- .github/workflows/grimoirelab-release.yml
This PR fixes a typo in the filename of the release notes.
> Fix typo in release workflow

- ADOPTERS.md
Sophia voiced the idea during the CHAOSS weekly sync to also include a list of papers that used GrimoireLab.
> Add research papers to ADOPTERS.md

- .github/workflows/docker-image.yml
- .github/workflows/grimoirelab-release.yml
- .github/workflows/release-grimoirelab-component.yml
- .github/workflows/release.yml
This commit updates the version of the actions because some of them are deprecated because Node 16 reached its end of life.
> [CI] Update the version of the actions in the workflows

- README.md
- docker-compose/README.md
This PR updates the README to include a link to the available visualizations for OpenSearch in the Sigils repository. Additionally, it adds a common question related to Mac users.
> Update documentation with a link to OpenSearch panels

- README.md
The non-commands element were copied together with terminal commands and caused errors (or extra work) for anyone following the instructions.
Signed-off-by: Georg J.P. Link <linkgeorg@gmail.com>
> Remove non-command elements from terminal commands

- .github/workflows/grimoirelab-release.yml
This PR fixes a bug in the workflow that prevented the NEWS file from being updated. The issue occurred because a boolean input in the `if` condition must be compared with a boolean value. Additionally, the boolean input in the run section must be compared as a string.
> Fix missing release notes in NEWS file

- community_components.md
@sduenas advised to add a community link for deploying GrimoireLab with AWS Fargate instead of contributing the deployment directly to GrimoireLab repository.
Ref: https://github.com/chaoss/grimoirelab/pull/659
> Added deployment sections and a link to running GrimoireLab with AWS Fargate

- docker/Dockerfile
This PR removes the installation of Python 3 and associated packages from the Dockerfile. These packages were introducing a vulnerability related to `python-wheel`. This change eliminates the risk by removing the unnecessary packages because Python has already been installed.
> Remove python3 installation from Dockerfile

- docker-compose/docker-compose-opensearch.yml
- docker-compose/docker-compose-secured.yml
- docker-compose/docker-compose.yml
This PR updates the path for the SortingHat static files served by NGINX due to the switch to a different Python version.
> Fix SortingHat static files path

- .github/workflows/docker-image.yml
- .github/workflows/grimoirelab-release.yml
- .github/workflows/release-grimoirelab-component.yml
- .github/workflows/release.yml
- docker-compose/docker-compose-opensearch.yml
- docker-compose/docker-compose-secured.yml
- docker-compose/docker-compose.yml
- docker/Dockerfile
- poetry.lock
- pyproject.toml
- releases/unreleased/python-minimum-version-updated.yml
Python 3.8 will reach its end of life in October 2024, and Python 3.9 will become the minimum version required by the project.
Update the GitHub workflows to run tests for Python 3.9, 3.10, 3.11 and 3.12 for future releases.
Update Docker images and docker-compose files to use Python 3.9
Related to https://github.com/chaoss/grimoirelab/issues/699
> Drop Python 3.8 support

- CONTRIBUTING.md
- GOVERNANCE.md
- SECURITY.md
This document describes the GrimoireLab security policies, including how to report vulnerabilities.
> Add Security Policy document

- .github/workflows/grimoirelab-release.yml
- .github/workflows/release-grimoirelab-component.yml
- .github/workflows/release.yml
- ADOPTERS.md
- docker-compose/README.md
- docker/Dockerfile
- docs/_includes/footer.html
- docs/index.html
Update files to support the migration of GrimoireLab repositories as part of the default branch transition from master to main.
> Migrate files for branch rename from master to main

- README.md
- docker-compose/README.md
- docker-compose/docker-compose-development.yml
This commit includes the `docker-compose-development.yml` file to deploy the required services for running GrimoireLab in development mode.
By default, it includes MariaDB running on port 3306, Redis on port 6379, OpenSearch on port 9200, and OpenSearch Dashboards on port 5601.
> [docker] Include Docker Compose file for development

- FreeBSD.md
- README.md
This patch adds necessary documentation for deploying Grimoirelab on a
FreeBSD system utilizing the FreeBSD ports/pkg system. Although this
documentation is based on FreeBSD this documentation will also be
helpful for someone who is planning to deploy Grimoirelab from source
without the need of any other container system like Docker.
Sponsored by: The FreeBSD Foundation
> Add FreeBSD documentation

- .github/workflows/tests.yml
- tests/utils.py
This PR adds a manual workflow to run end-to-end tests whenever `poetry.lock`, the `tests` directory, or the workflow itself is updated.
> [CI] GitHub Actions workflow for end-to-end testing

- poetry.lock
- pyproject.toml
Pin networkx to version 3.2.1 for compatibility with Python 3.9. The release was failing because the package was generated using the latest version of Python, and the latest version of networkx is not compatible with Python 3.9.
> [poetry] Pin networkx dependency for Python 3.9

- .github/workflows/release.yml
- poetry.lock
- pyproject.toml
Set the Python version to 3.9 to build the GrimoireLab package. This ensures compatibility with the lowest supported Python version when generating the package.
> [release] Build GrimoireLab package using Python 3.9

- docker/Dockerfile
This PR updates the image to use Python 3.12 instead of Python 3.9, and the latest stable version of Debian 12 (Bookworm).
Related to https://github.com/chaoss/grimoirelab/issues/779
> [docker] Update base image to Python 3.12 Debian 12

- .github/workflows/docker-image.yml
Update the way the images are signed using cosign. Use the GitHub OIDC Token instead of a custom private key.
> [ci] Modify Docker image signing process
