chaoss/grimoirelab

utils/README.md, utils/build_grimoirelab
* New flag to install all modules at once (by default, they are installed one by one, which seems to be more strict when checking dependencies among modules). This makes elasticgirl.17 fail, because a wrong dependency.
* Refactoring of the code. Now most of it is based on classes, with much more reuse, and a more clear structure.
* New flag for running checks. A check for changes in version has been included as well.
=> [build_grimoirelab] Refactoring, atonce and checks

releases/latest
This link would help to testing machinery, and in general to
any script interested in consuming the latest release.
=> [releases] Add link to latest release

tests/Dockerfile, tests/setup.cfg
Dockerfile needs to apt install a dbm package.
setup.cfg needs to be updated due to change in sortinghat.
=> [tests] Fix minor issues in configuration

docker/build_grimoirelab, utils/build_grimoirelab
Minor change, to merge after grimoirelab/GrimoireELK#155.
=> [build_grimoirelab] Change package name for kidash.

docs/README.md
=> Fix reference to chaoss.github.io/grimoirelab

README.md
Add a description of GrimoireLab.
Add a list of repositories for GrimoireLab.
Add a reference to the docker directory where configuration files for containers are available.
=> [README] List of GrimoireLab repositories and misc stuff

docs/_includes/navigation.html, docs/index.html
=> Solves #72

docker/identities.yaml, docker/mordred-dashboard.cfg, docker/projects.json
Small tweaks for Mordred configuration.
Improved list of CHAOSS projects.
Improved identities file.
=> [docker] Improved configuration files

README.md
After the successful voting, two new components are added to GrimoireLab: Bestiary and Hatstall.
=> [README] Add two new repositories

docs/index.html
=> [Website] Fix about link

docker/Dockerfile-secured, docker/README.md, docker/entrypoint-secured.sh, docker/mordred-dashboard.cfg, docker/projects.json
For grimoirelab/secured, new certificates and stuff.
For the list of projects, some update of repos.
For Mordred configuration, new stuff for studies.
For README.md, how to test that proxies work.
=> [docker] Some changes, to improve docker images.

utils/README.md, utils/build_grimoirelab
`--fail` argument now makes build_grimoirelab fail when tests, checks or build fail.
=> [build_grimoirelab] Make it fail when --fail is argument

docker/README.md, docker/ansible_build_tag.yml, docker/ansible_push.yml, docker/ansible_release.yml
Some playbooks for building pip packages and Docker images.
=> [docker] Add ansible playbooks

CONTRIBUTING.md
=> again fixing link

docker/Dockerfile-installed, docker/README.md, docker/ansible_release.yml, docker/entrypoint-full.sh, docker/entrypoint-secured.sh, utils/build_grimoirelab
Several commits to improve testing support (and fixes to minor issues).
Please, see the text for each commit to learn more details.
=> Improve testing

docker/ansible_release.yml, docker/menu.yaml
The file menu.yaml needs data about index patterns.
Fix ansible file so that it works when checking (and there is no real output from commands).
=> [docker] Fix stuff so that it works for 18.07-06

docker/mordred-infra-ssl.cfg, docker/mordred-infra.cfg
And add new comment in infra file.
=> [docker] Fix infra file for SSL

docker/projects.json
New schema for CHAOSS mailing lists.
New CHAOSS repositories for Augur.
=> [docker] Fix porjects.json with some modifications.

docker/Dockerfile-full, docker/Dockerfile-secured
This uses Elasticsearch and Kibiter 6.1.4.
Changes provided by chaoss/grimoirelab-sirmordred#232 are needed for this patch to work, so please merge only after this one is merged.
=> [docker] Changes to work with kibiter 6.1.4

docs/index.html
Missing GitLab as supported data source in the website
=> Add GitLab (Issues & Merge Requests)

docker/Dockerfile-installed, docker/aliases.json, docker/menu.yaml, docker/mordred-infra-ssl.cfg, docker/mordred-infra.cfg
Minor changes to adapt to the new configuration options and similar stuff.
=> Adapting to 0.2.0 (pkgs and Docker images)

BUILDING.md, docker/ansible_release.yml
Minor stuff to fix some details.
=> [release] Fix some minor stuff related to the production of releases

README.md
Renaming to be consistent with the usual practice.
=> Rename Elk to GrimoireElk

docs/ar/index.html
This PR fixes the problem when loading the scene in a Chrome browser for Android.
=> Load main js at the end in order to fix loading problems

docker/menu.yaml, docker/mordred-dashboard.cfg, utils/build_grimoirelab
This release includes perceval-finos, and build_grimoirelab needs to be updated for that.
Some minor changes to the configuration for mordred, tweaking timings, and to the menu, to include new panels.
Signed-off-by: Jesus M. Gonzalez-Barahona <jgb@gsyc.es>
=> Adapt to new release.

docs/_includes/header.html
https://chaoss.community/projects is not available anymore.
=> Dead link in the header

utils/build_grimoirelab
Signed-off-by: Jesus M. Gonzalez-Barahona <jgb@gsyc.es>
=> Add graal to the list of Python modules built for release.

README.md
I was looking for the kibiter repo and could not find it in the list... so I'm adding it.
=> Add Kibiter to list of GrimoireLab repos

README.md, default-grimoirelab-settings/aliases.json, default-grimoirelab-settings/organizations.json, default-grimoirelab-settings/projects.json, default-grimoirelab-settings/setup-secured.cfg, default-grimoirelab-settings/setup.cfg, docker-compose/README.md, docker-compose/docker-compose-secured.yml, docker-compose/docker-compose.yml, docker/README.md
This PR tries to solve #220 and chaoss/grimoirelab-tutorial#91
=> Add basic docs and config files to deploy GrimoireLab with docker-compose

README.md
Fix #222 
Signed-off-by: J. Manrique Lopez de la Fuente <jsmanrique@bitergia.com>
=> Fix #222: Wrong links to GrimoireLab website and tutorial

docs/_data/builtwith.yml
Signed-off-by: J. Manrique Lopez de la Fuente <jsmanrique@bitergia.com>
=> Fix broken link to Samsung OSG dashboards in website

README.md
Signed-off-by: J. Manrique Lopez de la Fuente <jsmanrique@bitergia.com>
=> Add info about git, docker, and docker-compose versions in README.md

default-grimoirelab-settings/organizations.json, docker/orgs.json, tests/orgs_file
Small fix, making sure VMware is capitalized correctly in the org files.
Signed-off-by: jonasrosland <jrosland@vmware.com>
=> Fix incorrect VMware capitalization

default-grimoirelab-settings/identities.yml
Running the instructions in the main README.md fails for docker-compose. It's missing an identities.yml file in the config directory
=> adding identities file for docker-compose setup

README.md
This code sets the bold font for software and hardware requirements for both docker and docker-compose installation options.
Fixes https://github.com/chaoss/grimoirelab/issues/231
=> [README] Highlight software and hardware requirements

docker-compose/docker-compose-secured.yml
This PR updates the image version number, which is now 0.2.33.
=> update docker compose secured settings

docker-compose/README.md
closes #250 
I'm trying to explain what the difference is between the non-secured and secured docker-compose solutions.
=> explain difference between docker composed files for secured vs. non-secured

third-party/README.md
This code showcases the 3p image via an example, which has been developed at https://github.com/chaoss/grimoirelab/pull/230
=> [third-party] Add example to use third party image

default-grimoirelab-settings/aliases.json, default-grimoirelab-settings/setup.cfg
Purpose of this PR is explained in https://github.com/chaoss/grimoirelab/issues/264.
PS: Hi @sanacl, @jsmanrique, @acs, @dicortazar, and @jgbarah. Even though I am not Mozilla Staff any longer, I keep using Grimoirelab. It rocks! 🎉
=> Made gitlab issues naming consistent. Fixes #264.

default-grimoirelab-settings/menu.yaml, default-grimoirelab-settings/setup-pip.cfg
This code includes 2 configuration files (menu.yml and setup-pip-cfg) to showcase the execution of grimoirelab using pip installation.
=> [default-grimoirelab-settings] Add menu.yml and setup-pip.cfg

third-party/README.md
Signed-off-by: Valerio Cosentino <valcos@bitergia.com>
=> [third-party] Fix examples URL to access data via ES

third-party/README.md
Related to https://github.com/chaoss/grimoirelab/issues/258
=> [third-party] Update URL of cross-nlp-rest-api

CONTRIBUTING.md
This commit updates the doc for contributing to
GrimoireLab. Some guidelines have been added
to write good commit messages.
Signed-off-by: Animesh <animuz111@gmail.com>
=> [doc] Added guidelines to write commit messages

docker-compose/README.md
This commit fixes a broken link
found in docker-compose README
Signed-off-by: animesh <animuz111@gmail.com>
=> [doc] Fix broken link

docs/index.html
Signed-off-by: Jose Manrique Lopez de la Fuente <jsmanrique@bitergia.com>
=> Add missing data sources

README.md
The GrimoireLab got updated to a newer version (ES & Kibiter 6.8.6). This PR updates the README.md with the latest snapshot of it.
Ref: #329
=> Update README.md with new image

default-grimoirelab-settings/setup-secured.cfg
Update defaults to use correct in_index per advice here.
Fixes #353
Signed-off-by: Ruth Cheesley <ruth.cheesley@acquia.com>
=> Update to correct in_index

CONTRIBUTING.md, README.md
Signed-off-by: kritisingh1 <kritisingh1.ks@gmail.com>
The pull request fixes some of the typos, grammatical and punctuation errors in the README.md and CONTRIBUTING.md files.
=> Fixes typo and grammatical errors

default-grimoirelab-settings/aliases.json
See https://github.com/chaoss/grimoirelab/issues/404#issuecomment-760512973
=> Make aliases.json consistent with setup.cfg

docs/index.html
Signed-off-by: Jose Manrique Lopez de la Fuente <jsmanrique@bitergia.com>
=> Remove Hackoctoberfest section from the webpage

README.md
Add a citation reference for the paper on GrimoireLab.
=> [README] Add citation

docs/_includes/data-sources.html
This PR adds a way to link directly to the list of supported data sources on the GrimoireLab Website
=> add anchor for data sources on website

default-grimoirelab-settings/menu.yaml
https://github.com/chaoss/grimoirelab/issues/441
Signed-off-by: Yehui Wang <yehui.wang.mdh@gmail.com>
=> fix typos to remove  warning logs

.github/workflows/grimoirelab-release.yml, .github/workflows/reusable-module-release.yml
This PR updates the release workflow in order to include some release changes.
This only include some details releated with the GrimoireLab release.
=> [gha] Update release workflow to include GrimoireLab changes

.github/workflows/grimoirelab-release.yml, .github/workflows/release-grimoirelab-component.yml
This PR fixes some errors raised during the first Grimoirelab release candidate.
=> [release] Fix some errors in Grimoirelab release

.github/workflows/grimoirelab-release.yml
This commit includes some dependencies to sirmordred to fix issues related to Poetry.
Depends on https://github.com/chaoss/grimoirelab-sirmordred/pull/565
=> [release] Update sirmordred dependencies

.github/workflows/grimoirelab-release.yml, .github/workflows/release-grimoirelab-component.yml
Call 'poetry update' for each package every time a new version is created. This change causes all dependencies
for each package to have the same version.
=> [release] Update all Poetry dependencies each release

.github/workflows/grimoirelab-release.yml
This PR updates the release workflow to refresh the GrimoireLab submodules every time a new release is created.
Closes https://github.com/chaoss/grimoirelab/issues/529
=> [release] Update src submodules each release

.github/workflows/grimoirelab-release.yml
This commit updates the release workflow to automatically update the version of GrimoireLab in the Dockerfile.
=> [docker] Update GrimoireLab version in the Dockerfile automatically

.github/workflows/grimoirelab-release.yml, .github/workflows/release-grimoirelab-component.yml
This PR updates the workflows to include the secrets in environments to have more control over the execution.
=> [actions] Include action secrets in environments

poetry.lock, pyproject.toml
Update Python version to 3.7.1
=> Update Python version to 3.7.1

.github/workflows/docker-image.yml
This PR updates the Docker workflow to generate images for amd64 and arm64.
Related to https://github.com/chaoss/grimoirelab/issues/550
=> [docker] Generate docker images for ARM64 architecture

ROADMAP.md
The document includes the set of themes that we will use to classify and to define tasks that will help us to reach the goals of the roadmap.
=> Add initial themes to the roadmap

.github/workflows/grimoirelab-release.yml, .github/workflows/release-grimoirelab-component.yml
This PR updates the release workflow. It includes a new option to execute the release forcing a new major version of all the GrimoireLab packages.
=> [release] Option to bump major version of all packages

releases/custom_release_notes.md
We're going to include custom notes on the major release. We need to check whether they are included when GitHub actions workflows run.
=> Add custom notes for testing CI workflow

releases/custom_release_notes.md
Include the notes we want to include for this release.
=> Add custom notes for GrimoireLab 1.0.0

ADOPTERS.md
Adding URJC description, and the original GrimoireLab paper.
=> ADOPTERS: Add URJC

ADOPTERS.md
This patch adds the OpenInfra Foundation to the ADOPTERS.md file with a brief description of how the rganization is using the project.
=> Adding the OpenInfra Foundation as supporter

docker-compose/docker-compose-opensearch.yml
Update the OpenSearch images versions and include
volumes to store the data.
=> Update Opensearch images in the docker compose

ADOPTERS.md
Add GR-OSS url and brief sentence to list of GrimoireLab adopters, as per Georg Link request. 😄
=> Add GR-OSS to ADOPTERS.md

ADOPTERS.md
I also sorted the list to have the newest publication at the top
=> Add paper "Estimating Usage of Open Source Projects" to ADOPTERS.md

README.md
This PR includes documentation about the changes in the latest version related to permission groups.
=> [readme] Permissions groups breaking change

docs/_includes/footer.html
With this pixel we can track the activity on our website.
Related to #689, #690.
=> Add scarf pixel to the website

ROADMAP.md
These changes update the objectives and themes that leads us to the release of GrimoireLab 2.0.
=> Update ROADMAP for GrimoireLab 2.0

docker-compose/docker-compose.yml, docker/Dockerfile, poetry.lock
This PR updates the Docker Compose file to include OpenSearch for storing events collected by GrimoireLab Core. It also adds Archivist workers for event storage.
=> [2.x] Update docker compose to use OpenSearch for storing events

ADOPTERS.md
Adding research paper that utilizes Perceval in its methods.
=> Adding research paper to ADOPTERS

ADOPTERS.md
Added my research paper referencing to GrimoireLab
=> Add research paper

poetry.lock
Update GrimoireLab dependencies to the latest version
=> [2.x] Update GrimoireLab dependencies

default-grimoirelab-settings/setup.cfg, docker-compose/docker-compose.yml
Updated docker-compose and configuration files to use OpenSearch 3, which introduces significant improvements in  performance, scalability, and search capabilities.
=> Update docker compose file to use OpenSearch 3
